feat(entproto): validate inputs during extraction
ent/contrib pull request #92
Opened 2021-06-30 23:04 UTC by tarrencev

this pr removes the pre-marshal validation step for type marshaling. instead, the validation is done during marshaling.

2021-07-01 08:09 UTC, rotemtam requested changes
hey @tarrencev,
thanks so much for picking this up. its a great improvement to the codebase and the generated code is much better this way. please find a few minor comments from me 🙏

2021-07-01 08:09 UTC, rotemtam commented on go.mod
> -	github.com/google/addlicense v0.0.0-20200906110928-a0294312aa76 // indirect
not sure why these were removed?

2021-07-01 08:09 UTC, rotemtam commented on entproto/cmd/protoc-gen-entgrpc/converter.go
> +func (g *serviceGenerator) renderToEnt(conv *converter, varName, ident string) string {
this method became a bit tough to parse mentally. i like the generated code, but maybe we can express this with an inline template for each use case?

2021-07-01 14:50 UTC, tarrencev commented on entproto/internal/todo/ent/proto/entpb/entpb.pb.go
> +	empty "github.com/golang/protobuf/ptypes/empty"
hmm i ran with `libprotoc 3.17.3` but this import didn't change

2021-07-01 14:51 UTC, tarrencev commented on go.mod
> -	github.com/google/addlicense v0.0.0-20200906110928-a0294312aa76 // indirect
`go mod tidy` decided to remove it

2021-07-01 14:53 UTC, tarrencev commented on entproto/cmd/protoc-gen-entgrpc/template.go
> +	if templateTokens.MatchString(out) {
since right now there are template strings given as vars (to pass the templated grpc status errors)

2021-07-04 04:18 UTC, rotemtam commented
@tarrencev looks much better, thanks again for working on this. 
just notice that CI is still red on go generate diffs , to fix it I would just revert the changes to go.mod/go.sum (yes there's an issue here that we need to do `go generate` after tidy. there's a fix for this and ill pick it up soon 🙏

2021-07-04 04:46 UTC, tarrencev commented
@rotemtam i reverted go.mod and go.sum to `origin/master`. could you please try CI again? (is it possible to run automatically? =/)

2021-07-04 08:40 UTC, merged

2021-07-04 08:40 UTC, a8m commented
Thanks for your contribution @tarrencev 😃